stages:
  - pull_prod
  - build_prod
  - clear_prod
  - pull_stage
  - build_stage
  - clear_stage

pull_code_prod:
  stage: pull_prod
  tags:
    - crm
  only:
    - main
  script:
    - cd /home/web/cabinet-frontend/prod
    - sudo -H -u web git pull

build_prod:
  stage: build_prod
  tags:
    - crm
  only:
    - main
  script:
    - cd /home/web/cabinet-frontend/prod
    - /usr/bin/docker compose -p cabinet-prod -f docker-compose.stage.yml up --build -d

clear_prod:
  stage: clear_prod
  tags:
    - crm
  only:
    - main
  script:
    - cd /home/web
    - docker image prune -af
    - docker builder prune -af

pull_code_stage:
  stage: pull_stage
  tags:
    - crm
  only:
    - dev
  script:
    - cd /home/web/cabinet-frontend/stage
    - sudo -H -u web git pull

build_stage:
  stage: build_stage
  tags:
    - crm
  only:
    - dev
  script:
    - cd /home/web/cabinet-frontend/stage
    - /usr/bin/docker compose -p cabinet-stage -f docker-compose.stage.yml up --build -d

clear_stage:
  stage: clear_stage
  tags:
    - crm
  only:
    - dev
  script:
    - cd /home/web
    - docker image prune -af
    - docker builder prune -af